language: go

os: windows

before_install:
  - go get -t -v ./...

before_deploy:
  - GOARCH=amd64 GOOS=windows go build -o watermark.exe
  - 7z.exe a watermark.zip watermark.exe demo.jpg watermark.png

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: 
    - watermark.zip
  skip_cleanup: true
  on:
    tags: true

