language: go

go:
  - tip

before_install:
  - go get github.com/golang/sys/windows/registry
  - go get -t -v ./...

script:
  - go test -v ./...

before_deploy:
  - GOARCH=amd64 GOOS=windows go build -o watermark.exe
  - zip -r watermark.zip watermark.exe demo.jpg watermark.png

deploy:
  provider: releases
  api_key: "${GH_TOKEN}"
  file: 
    - watermark.zip
  skip_cleanup: true
  on:
    tags: true
